### ISSUE TITLE
Is it possible to change the name of the MIDI Device?

### ISSUE THREAD

**Issue by Kprellz** [lathoub/Arduino-USBMIDI#4]
Hey! Not really an issue as much as just a question. I'm using a Metro M0 Express, I'm wondering if theres a way to change the name that applications see when this is plugged in, currently programs see it is "Metro M0 Express" But i'm not sure where or how it see's that info and if theres a way to change it?

**Comment by lathoub** [comment]
Hey @Kprellz, unfortunately not easy...
see https://github.com/FortySevenEffects/arduino_midi_library/issues/175
